# Generated by Django 5.2.8 on 2026-01-27 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantier_app', '0001_initial'),
        ('secretaire_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Reparation appareil, Achat tole, Location camion, Salaire ouvrier', max_length=200, unique=True)),
                ('categorie', models.CharField(choices=[('materiaux', 'Matériaux'), ('transport', 'Transport'), ('main_oeuvre', "main d'oeuvre"), ('frais_divers', 'Frais divers'), ('administration', 'Administration'), ('autre', 'Autre')], default='materiaux', help_text='choix du type de depense', max_length=50)),
                ('couleur', models.CharField(choices=[('#FF6384', 'Rouge'), ('#36A2EB', 'Bleu'), ('#9966FF', 'Violet'), ('#FFCE56', 'Jaune'), ('#4BC0C0', 'Turquoise'), ('#FF9F40', 'Orange')], default='#FF6384', help_text='Choix de la couleur pour type de depense', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description détaillé du ty de depense')),
                ('est_actif', models.BooleanField(default=True, help_text="Désactiver pour masquer ce type sans supprimer l'historique")),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage dans les liste déroulantes")),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de depense',
                'verbose_name_plural': 'Type de dépense',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RapportDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiau_article', models.CharField(blank=True, max_length=200, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantité', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fournisseur_not_db', models.CharField(blank=True, max_length=75, null=True)),
                ('facture', models.ImageField(blank=True, null=True, upload_to='images/photo_facture')),
                ('date_depense', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'validé'), ('rejete', 'Rejeté'), ('modifier', 'Demander des modifications')], default='brouillon', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='chantier_app.chantier')),
                ('demande_decaissement', models.ForeignKey(blank=True, help_text="Lien avec la demande d'argent préalable", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_depense', to='secretaire_app.demandedecaissement', verbose_name='Demande de décaissement liée')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_depense', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='employee_app.fournisseur')),
                ('type_depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='employee_app.typedepense')),
            ],
            options={
                'verbose_name': 'Rapport de depense',
                'verbose_name_plural': 'Rapports de depense',
                'ordering': ['-date_creation'],
            },
        ),
    ]
