# Generated by Django 5.2.8 on 2025-11-29 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantier_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RapportDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiau_article', models.CharField(blank=True, max_length=200, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantité', models.IntegerField(default=0)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('facture', models.ImageField(blank=True, null=True, upload_to='images/photo_facture/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chantier_app.chantier')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.typedepense')),
            ],
        ),
    ]
