# Generated by Django 5.2.8 on 2025-12-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportdepense',
            name='fournisseur_not_db',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
