# Generated by Django 5.2.8 on 2026-01-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantier_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_contrat', models.CharField(max_length=50, unique=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Comptant'), ('tranche', 'Tranche'), ('credit', 'Crédit'), ('autre', 'Autre')], default='comptant', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acompte_pourcentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('nombre_tranches', models.IntegerField(default=1)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_du_dernier_paiement', models.DateField(blank=True, null=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('devis_initial', models.FileField(blank=True, null=True, upload_to='devis/')),
                ('garantie_mois', models.IntegerField(default=12)),
                ('notes_contractuelles', models.TextField(blank=True, null=True)),
                ('chantier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='chantier_app.chantier')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='TranchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tranche', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_prevue', models.DateField()),
                ('date_reelle', models.DateField(blank=True, null=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='contrat_app.contrat')),
            ],
            options={
                'verbose_name': 'Tranche de Paiement',
                'verbose_name_plural': 'Tranches de Paiement',
                'ordering': ['numero_tranche'],
            },
        ),
    ]
