# Generated by Django 5.2.8 on 2025-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='referenre_contrat',
            new_name='reference_contrat',
        ),
    ]
