# Generated by Django 5.2.8 on 2026-01-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantier_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDecaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.TextField()),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee_directeur', 'Approuvée par Directeur'), ('refusee_directeur', 'Refusée par Directeur'), ('approuvee_comptable', 'Approuvée par Comptable'), ('refusee_comptable', 'Refusée par Comptable')], default='en_attente', max_length=50)),
                ('decaisse', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_decaissement', models.DateTimeField(blank=True, null=True)),
                ('reference_demande', models.CharField(blank=True, max_length=50, null=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chantier_app.chantier')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
