# Generated by Django 5.2.8 on 2025-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedecaissement',
            name='decaisse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandedecaissement',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuvee_directeur', 'Approuvée par Directeur'), ('refusee_directeur', 'Refusée par Directeur'), ('approuvee_comptable', 'Approuvée par Comptable'), ('refusee_comptable', 'Refusée par Comptable')], default='en_attente', max_length=50),
        ),
    ]
