# Generated by Django 5.2.8 on 2025-12-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandedecaissement',
            old_name='nom',
            new_name='demandeur',
        ),
        migrations.AddField(
            model_name='demandedecaissement',
            name='reference_demande',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
