# Generated by Django 5.2.8 on 2025-11-29 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('nom_chantier', models.CharField(max_length=200)),
                ('adresse_chantier', models.CharField(max_length=100)),
                ('quartier_chantier', models.CharField(blank=True, max_length=100, null=True)),
                ('ville_chantier', models.CharField(blank=True, max_length=100, null=True)),
                ('pays_chantier', models.CharField(max_length=100)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type_travaux', models.CharField(choices=[('charpente_metallique', 'Charpente Métallique'), ('toiture_tole', 'Toiture en Tôle'), ('couverture', 'Couverture'), ('isolation', 'Isolation'), ('ventilation', 'Ventilation'), ('etancheite', 'Étanchéité'), ('garde_corps', 'Garde-Corps'), ('escalier_metal', 'Escalier en Métal'), ('porte_grillee', 'Porte/Grille Métallique'), ('mixte', 'Travaux Mixtes'), ('autre', 'Autre')], max_length=50)),
                ('type_batiment', models.CharField(choices=[('maison_individuelle', 'Maison Individuelle'), ('appartement', 'Appartement'), ('entrepot', 'Entrepôt'), ('usine', 'Usine'), ('bureau', 'Bureau'), ('commerce', 'Commerce'), ('ferme', 'Batiment Agricole'), ('batiment_public', 'Batiment Public'), ('autre', 'Autre')], max_length=50)),
                ('surface_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hauteur_batiment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description_detaille', models.TextField(blank=True, null=True)),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('duree_estimee', models.IntegerField(blank=True, null=True)),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_materiaux_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_main_oeuvre_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('marge_beneficiaire_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_chantier', models.CharField(choices=[('devis', 'Devis en Cours'), ('planification', 'Planification'), ('en_cours', 'En Cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('facturee', 'Facturée'), ('paye', 'Payée'), ('annule', 'Annulé')], default='devis', max_length=50)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('plans_joins', models.BooleanField(default=False)),
                ('photos_avant', models.BooleanField(default=False)),
                ('photos_apres', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chef_de_chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_chef', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
            },
        ),
    ]
