# Generated by Django 5.2.8 on 2025-12-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantier_app', '0001_initial'),
        ('client_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chantier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='client_app.client'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='equipe_affectee',
            field=models.ManyToManyField(blank=True, related_name='chantiers_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
