# Generated by Django 5.2.8 on 2026-01-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('institution', 'Institution publique'), ('promoteur', 'Promoteur immobilier'), ('autre', 'Autre')], max_length=50)),
                ('raison_sociale', models.CharField(blank=True, max_length=200, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('secteur_activite', models.CharField(blank=True, choices=[('residential', 'Résidentiel'), ('commercial', 'Commercial'), ('industriel', 'Industriel'), ('agricole', 'Agricole'), ('public', 'Public')], max_length=50, null=True)),
                ('source_client', models.CharField(blank=True, choices=[('recommendation', 'Recommandation'), ('site_web', 'Site Web'), ('reseaux_sociaux', 'Réseaux Sociaux'), ('publicite', 'Publicité'), ('ancien_client', 'Ancien Client'), ('autre', 'Autre'), ('salon', 'Salon Professionnel')], max_length=50, null=True)),
                ('notes_internes', models.TextField(blank=True, null=True)),
                ('potentiel_client', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], default='moyen', max_length=20, null=True)),
                ('date_premier_contact', models.DateField(auto_now_add=True)),
                ('est_fidel', models.BooleanField(default=False)),
                ('chiffre_affaires_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commercial_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_attaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
