# Generated by Django 5.2.8 on 2025-12-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranchepaiement',
            name='contrat',
        ),
        migrations.DeleteModel(
            name='Contrat',
        ),
        migrations.DeleteModel(
            name='TranchePaiement',
        ),
    ]
